set-option -ga terminal-overrides ",*256col*:Tc"
set-window-option -g mode-keys vi
set -g mouse on

# To make HOME/END key work
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.config/tmux/plugins/tpm/tpm'

bind c new-window -c "#{pane_current_path}"

# Configuration for continuum
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# Stylization
set -g status off
set -g status-interval 0

set -g status-left ""
set -g status-right "%H:%M"

set -g mode-style "fg=#82aaff,bg=#3b4261"
set -g message-style "fg=#82aaff,bg=#3b4261"
set -g message-command-style "fg=#82aaff,bg=#3b4261"
set -g status-style "bg=default,fg=grey"
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#82aaff"
setw -g window-status-activity-style "underscore,fg=#828bb8,bg=#1e2030"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#828bb8,bg=#1e2030"
